### ISSUE TITLE
Jupyter server always exited while start

### ISSUE THREAD

**Issue by chakraroy** [MaelImhof/obsidian-jupyter#84] opened 2024-08-05 12:38 UTC
I have tried to enable this plugins in my MacBook, but always have problem with the Jupyter server exited message. when I run on windows using the same Conda, there is no issue, but with the same Conda I tried to run in Mac 2017 with Monterey, I always got the same messages. To open the jupyterlab or notebook manually using terminal, both, there is no issue at all. Is there any clue how to resolve this problem?

**Comment by MaelImhof** [comment] 2024-08-05 20:07
Hi there, thank you for opening this issue !

If I understood correctly, you are using the plugin both on Windows and macOS, and it works on Windows but not on macOS. When you start Jupyter using the command line, it works fine on both OS. Is that correct?

Here are some points that could help clarify and debug the issue. Let me know whether this helps.

## 1. Python executable path

Did you setup the Python executable path correctly?

If you are using a Conda environment, you must tell the plugin to use the Python of this Conda environment. In particular, make sure that

- The [Python executable path to use](https://jupyter.mael.im/settings#python-executable-to-use) dropdown has `Specified executable path` selected, otherwise the plugin will use a simple `python` command.
- The [Python executable path](https://jupyter.mael.im/settings#python-executable-path) is set to the full path of the Python executable.

For Conda in particular, you might be interested in [this short tutorial](https://jupyter.mael.im/miniconda-and-conda).

## 2. Jupyter logs

What's the error that is displayed? If Jupyter crashes while starting, it might have logged something that indicates the cause of the issue.

To figure it out :

- At the very bottom of the plugin's settings, check [Print Jupyter output to Obsidian console](https://help.obsidian.md/Help+and+support#Capture+console+logs). What Jupyter normally logs to the terminal once started will then be transferred to the Obsidian console.
- Open the [Obsidian console](https://help.obsidian.md/Help+and+support#Capture+console+logs) using the default (or your custom) key bindings.
- Start Jupyter using the plugin.
- There should be some recognizable Jupyter log messages appearing in the Obsidian  to help us debug this issue.

You can post an anonimized version of the logs (remove any sensitive information before posting it) so that I can take a look.

## 3. Command used to start Jupyter

What command do you use to start Jupyter when you start it manually from the terminal?

The plugin uses `[python executable] -m [notebook/jupyterlab]` depending on the Python executable you provide and whether you use Jupyter Notebook or Lab. Does this work if you run it in the command line?

**Comment by MaelImhof** [comment] 2024-08-05 20:08
I realize this is very tedious, I'll work on some features to ease debugging for the next release, like automated log export, better error handling and explanation, ...

**Comment by chakraroy** [comment] 2024-08-06 12:45
![Jepretan Layar 2024-08-06 pukul 19 44 43](https://github.com/user-attachments/assets/2d8e838a-54ff-4309-8cf3-5ff2d090344a)

I got those verbose message from console while running Jupyter server in intel Mac.

**Comment by MaelImhof** [comment] 2024-08-06 19:08
When I run the plugin on my machine, the first and the last messages are nowhere to be seen.

```
jupyter_server.extension.utils.ExtensionModuleNotFound : The module 'jupyter_nbextensions_configurator' could not be found (No module named 'jupyter_nbextensions_configurator'). Are you sure the extension is installed?
```

and

```
Interrupted...
```

- Do you use any custom configuration that requires the `jupyter_nbextensions_configurator` to be there?
- Maybe the extension *is* installed, but on another Python environment, have you checked the Python executable path you configured?

It might also be your OS that sends an interrupt signal to the child process running Jupyter, but that would be harder to debug...

**Comment by chakraroy** [comment] 2024-08-07 07:50
ok that's right, I remove the configurator and now it's running.... Thanks!

**Comment by MaelImhof** [comment] 2024-08-08 11:42
Glad it works for you, I'm going to close this issue as solved then.

Happy coding !

**Closed as completed** 2024-08-08 11:43 UTC
Labels: ask-for-help, beta
